### ISSUE TITLE
Error from `triggerSignalActivity` when using triggerURL from `getWorkflow`

### ISSUE THREAD

**Issue by duynguyen** [adobe/adobeio-cna-core-campaign-standard#11]
### Expected Behaviour

For `triggerSignalActivity`, one has to first call `getWorkflow`, which returns a URL for triggering signal activity. That URL is then called, with required parameters, to trigger a workflow.
As the URL returned by `getWorkflow` is a full URL, e.g. `https://mc.adobe.io/<ORGANIZATION>/campaign/workflow/execution/@19K_8ZhwSr_6KVriV4X8gw3YThAY-TAjJjV4vHmUiwTm_0kpgzQ-fa3x8KCLfb8FjjR53mJ22GYuLoaHLovKIuxoGXDvHXtuSSrLsbbT5PA9Dkezt6tzIA7hNTAR9oBun6cMHA/activities/activity/@19K_8ZhwSr_6KVriV4X8gw3YThAY-TAjJjV4vHmUiwTm_0kpgzQ-fa3x8KCLfb8FjjR53mJ22GYuLoaHLovKIgIFKtEyaPUqUf02xvnDBod6C2DYV0M8pVdXnSo-Xx2RMbKbAeJhFjtO0FUWO6WeouJQMcvkTwRhgdxyQ0nbh_jqAV11/trigger`, it needs to be called in a "request" lib manner rather than a path of Swagger def.

### Actual Behaviour

When calling `acsClient.triggerSignalActivity(triggerUrl, wfParams)`, we will get `Internal server error`, because with `triggerUrl` being https://mc.adobe.io/..., the actual call will be to `https://mc.adobe.io/adobeiosolutionsdemo/campaign/https://mc.adobe.io/adobeiosolutionsdemo/campaign/workflow/execution/...`.

#### Sample Code that illustrates the problem

```
const acsClient = await sdk.init(tenantId, authClientId, jwtToken)
const workflow = await acsClient.getWorkflow('myWkfId')
const wkfHref = workflow.body.activities.activity.signal1.trigger.href
await acsClient.triggerSignalActivity(processTriggerUrl(wkfHref), { source: 'API', parameters: { email: args.email } })
```

#### Logs taken while reproducing problem
```
Error while calling Adobe Campaign Standard triggerSignalActivity - Error: Internal Server Error
```

**Comment by shazron** [comment]
Duy, so in this case the ACS API docs are also incorrect then? https://docs.campaign.adobe.com/doc/standard/en/api/ACS_API.html#triggering-a-signal-activity

The docs clearly imply the url from `getWorkflow` is a relative url (`<TRIGGER_URL>`).

**Comment by shazron** [comment]
I've sent an email to the ACS API devs for clarification and cc'ed you. It's either a bug in the docs, or a bug in the API `getWorkflow` calls

**Comment by duynguyen** [comment]
@shazron , yep agree with you. We will see what they respond.

**Comment by shazron** [comment]
Looks like they updated the docs -- the trigger URL is actually an absolute URL. I'll fix the SDK with this in mind. Perhaps chain it with the workflowID to do both things in succession?  Or provide a general POST function like this general GET function: https://github.com/adobe/adobeio-cna-core-campaign-standard/blob/master/src/index.js#L571?

**Comment by duynguyen** [comment]
my personal preference would be to call one single method that does both. However there is potentially a problem with that approach, because there could be more than one activity per workflow to be triggered.
Hence the safe option for now is to go with the general POST function so that users can decide what exactly to be triggered.
