### ISSUE TITLE
getAllServices - Error: Not Found

### ISSUE THREAD

**Issue by dhindle** [adobe/adobeio-cna-core-campaign-standard#16]
After successfully initializing with the parameters (tenantID, apiKey, accessToken). Parameters have been tested with Postman. When calling `getAllServices`, I see the below error:
`Error: Error while calling Adobe Campaign Standard getAllServices - Error: Not Found` 

Can we change this to a more descriptive error?

**Comment by shazron** [comment]
Are you on a *nix system?
```
DEBUG=adobeio-cna-core-campaign-standard  <your_call_here>
```

Prepend that to the call that invokes your function. This should output a lot of debug data, you can paste the output to me privately.

**Comment by shazron** [comment]
The url request is malformed, when using `getAllServices()` with no parameters.
Example: `https://mc.adobe.io/<tenantid>/campaign/profileAndServices,/service/,`

**Comment by dhindle** [comment]
> Are you on a *nix system?
> 
> ```shell
> DEBUG=adobeio-cna-core-campaign-standard  <your_call_here>
> ```
> 
> Prepend that to the call that invokes your function, on the command line. This should output a lot of debug data, you can paste the output to me privately.

Can we add this to the documentation?

**Comment by shazron** [comment]
@dhindle issue added for docs: #17

**Comment by shazron** [comment]
Found the issue. When a path parameter is empty (the default), it thinks the default value is an array or an object (most likely the `undefined` object), it defaults to simple-style serialization, which separates the value with a comma: https://swagger.io/docs/specification/describing-parameters/

Workaround: explicitly set the parameters, don't allow `undefined` values.
